
--注释

CREATE TABLE IF NOT EXISTS KBAR (
    LEVEL VARCHAR(60)
    ,TRADING_DAY DATE
    ,OPEN DECIMAL(9,4)
    ,CLOSE DECIMAL(9,4)
    ,HIGH DECIMAL(9,4)
    ,LOW DECIMAL(9,4)
    ,BEGIN_TIME TIMESTAMP
    ,END_TIME TIMESTAMP
    ,HIGH_TIME TIMESTAMP
    ,LOW_TIME TIMESTAMP
    ,AVG DECIMAL(9,4)
    ,VOLUME BIGINT
    ,OPENINT BIGINT
    ,TURNOVER DECIMAL(10,4)
    ,AVG_PRICE DECIMAL(9, 4)
);
