
--TABLE PLAYBOOK
CREATE TABLE PLAYBOOK(
    ID VARCHAR(64)
    ,TRADING_DAY VARCHAR(24)
    ,STATE VARCHAR(32)
    ,ATTRS MEDIUMTEXT
    ,PRIMARY KEY(ID)
);

--TABLE ORDER
CREATE TABLE "ORDER"(
    ID VARCHAR(64)
    ,TRADING_DAY VARCHAR(24)
    ,STATE VARCHAR(32)
    ,ATTRS MEDIUMTEXT
    ,PRIMARY KEY(ID)
);
